### ISSUE TITLE
Setting editor.fontFamily to "Roboto Mono" leads to unknown unicode characters

### ISSUE THREAD

**Issue by olivierlacan** [GustavoMelloGit/copy-file-syntax-extension#1]
Bit of a strange one. 😅 

I tried this (very nice) extension with Menlo & Monaco as the editor fonts and everything went peachy. 

Text was copied at the expected font size, font face, colors. It all worked great! 

However, I noticed that if I set my fontFamily to this, the output is completely mangled: 

```json
"editor.fontFamily": "'Roboto Mono', Menlo, Monaco, 'Courier New', monospace"
```

<img width="1364" alt="image" src="https://github.com/GustavoMelloGit/copy-file-syntax-extension/assets/65950/7ecf844f-65be-40f9-8808-7023d2c47db1">

This amazingly might just be a bug in Keynote failing to recognize the font name identifier for `Roboto Mono` because it sets the Font to `.LastResort` which appears to be an error handling artifact. 

Funny enough if you manually change the Font to Roboto Mono, everything is back to normal. 

<img width="1612" alt="image" src="https://github.com/GustavoMelloGit/copy-file-syntax-extension/assets/65950/aedbb526-cd50-4e89-a0c5-3518a7ac1cff">

So this is unlikely an issue with this extension (I'll close it immediately) but I figured it might help others to document this strange behavior with fonts like "Roboto Mono" before they blame your code. 😄

**Comment by GustavoMelloGit** [comment]
Nice find, @olivierlacan! Thank you for opening this issue
